### PR TITLE
add affirm calendar/card icons from /mattress/trial

### PR DESCRIPTION
**Pull request by kylehotchkiss**
I added two icons to /lib/storefront.

I haven't compiled this before, so can somebody please inspect my output in /dist to verify it looks OK?

### CODE REVIEW

**Comment by ckeisato** [comment]
Before we add to nightshade-icons we do the following
-  Remove fills or use inline fills if the icon is always that color, we don't use classes for svgs
-  Add title and desc tags
-  Since these are being compiled into a spritesheet, you don't have to minimize them, but I think it's fine if you do.
Once the pr is merged, you can take a look at the contributing.md file in this repo to see how to up the version and stuff

**Comment by florida** [comment]
you can use this tool as well: https://jakearchibald.github.io/svgomg/

**Comment by kylehotchkiss** [comment]
thx @ckeisato / @florida - i will get both of these changes in.

**Comment by kylehotchkiss** [comment]
@ckeisato can you please give this one more look? thanks!

**Comment by ckeisato** [comment]
hey sorry I didn't see the tag yesterday, it looks good

**Comment by florida** [comment]
Looks good 2 me too 👍

**Comment by kylehotchkiss** [comment]
Thanks @ckeisato @florida! merging.

**Pull request merged**
