### PR TITLE
Match task to casper svg a11y workflow

### PR DESCRIPTION
**Pull request by robwierzbowski**
There are two breaking changes in this PR:
- Build spritesheets without doctype and xml namespace (necessary for inlining spritesheets implemented in CasperSleep/Casper#2320)
- Build spritesheets at new path (the built spritesheets are production content, so I moved them from the test folder)

**Reviewers, please let me know if any of our projects are currently referencing the spritesheet in `test/` directly.**

It also contains some general housekeeping: clean up some dead code, remove unnecessary characters/dependencies/etc., normalizing whitespace. 

**Before**: Spritesheets were generated with a doctype and xml namespace that broke inlining. Spritesheets were generated into a `test/`dir, although the sheets were used in Casper production.

**After**: Spritesheets contain only a top level `svg` element, allowing inlining. Spritesheets are generated into a `dist/`dir, one for each folder of sprites.

**Testing**: 
- Delete the `dist` directory and run `gulp`. Check that sheets are generated in a reasonable manner.
- Once this PR gets provisional LGTM, I'll post a link to a commit on Casper that imports and uses the storefront spritesheet. We can test in the app and then merge both PRs.

### CODE REVIEW

**Comment by misscs** [comment]
Hey, this looks good! I think you're taking it in a different direction than where it was which is fine until it becomes part of half-full directory. 

The reason I never had the gulp file in the root is because in my mind, this module only exports a function and to use it folks would import the function into their gulpfile. The idea behind having things in `test` was an example of how we would use it. In my mind, the "test" was proof that it works. 

I'm cool with the changes your proposing as an interim for now :)

**Comment by misscs** [comment]
LGTM. Please make sure to tag and push tags. `npm version -m "Bump version %s"` should take of everything

**Comment by robwierzbowski** [comment]
Cool. If we're going to use this as a repo to share svg spritesheets (as mentioned in the readme / our discussion), I think the gulpfile is part of the prod workflow. If not, the svg icons should be tracked somewhere else.

We could clear this up in the future by splitting into two single use repos, one that exports the task, and one that distributes a standardized set of icons to multiple projects (e.g., multiple i18n Ando repos).

**Comment by robwierzbowski** [comment]
I tried the `npm version` task, but it failed so I handled manually. Should have saved the error log...

**Pull request merged**
