### PR TITLE
Add google, linkedin, youtube

### PR DESCRIPTION
**Pull request by edwardsfriedman**

### CODE REVIEW

**Comment by robwierzbowski** [comment]
LGTM.

**Comment by robwierzbowski** [comment]
Actually, wait a sec.

**Comment by edwardsfriedman** [comment]
ok!

**Comment by robwierzbowski** [comment]
Each of these should have at least a `title`. Forgot about that for @victorwhy's latest icon PR as well.

I don't remember if Illustrator has a method for adding titles at the svg generation level or if we'll have to always manage manually. We should examine next week.

**Comment by edwardsfriedman** [comment]
Oh right of course! My bad.

**Comment by robwierzbowski** [comment]
DTM.

**Pull request merged**
